# Generated by Django 2.1.15 on 2022-06-20 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_type', models.CharField(blank=True, max_length=200, null=True)),
                ('config', models.CharField(blank=True, max_length=2000, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('synonym', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUsedIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='IntentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('synonym', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Entity')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='RequireVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_bot.Intent')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('variable_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='requirevariables',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Step'),
        ),
        migrations.AddField(
            model_name='requirevariables',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Variable'),
        ),
        migrations.AddField(
            model_name='historyusedintent',
            name='intent',
            field=models.ForeignKey(on_delete=None, to='chat_bot.Intent'),
        ),
        migrations.AddField(
            model_name='historyusedintent',
            name='step',
            field=models.ForeignKey(on_delete=None, to='chat_bot.Step'),
        ),
        migrations.AddField(
            model_name='historychat',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Step'),
        ),
        migrations.AddField(
            model_name='historychat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.User'),
        ),
        migrations.AddField(
            model_name='historychat',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Variable'),
        ),
        migrations.AddField(
            model_name='card',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Step'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.User'),
        ),
    ]
