# Generated by Django 2.1.15 on 2022-09-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historychat',
            name='user',
        ),
        migrations.AddField(
            model_name='historychat',
            name='user_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
