# Generated by Django 2.1.15 on 2022-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_chatvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot'),
        ),
    ]
