# Generated by Django 2.1.15 on 2022-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0004_variable_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot'),
        ),
        migrations.AddField(
            model_name='step',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='chat_bot.Bot'),
        ),
    ]
